parameters:
#    lyra_demo.example.class: Lyra\DemoBundle\Example

services:
#    lyra_demo.example:
#        class: %lyra_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
